### ISSUE TITLE
API Testing Error

### ISSUE THREAD

**Issue by puriaayush01** [OWASP/OFFAT#45]
I'm encountering an error whenever I attempt to test an API (which is an open-source API). However, when I utilize the following link (https://petstore.swagger.io/v2/swagger.json), the OFFAT Tool functions properly. Could you kindly assist me with resolving this issue?

<img width="724" alt="Error-OFFAT" src="https://github.com/OWASP/OFFAT/assets/110390926/89a76418-cf75-4927-afa3-ea6c6627a7a8">

**Comment by dmdhrumilmistry** [comment]
Hey @puriaayush01,

From image I can see that you're currently using python version 3.12. I've recently discovered that packages that we're using is crashing due to bug mentioned [here](https://github.com/python-openapi/openapi-spec-validator/issues/327).

You try using offat with python 3.11 until this is resolved. 

Marking this as resolved for now. If you're still facing issues then feel free to reopen this one.

**Comment by dmdhrumilmistry** [comment]
This issue has been resolved. Please install latest version of the tool from pypi.

**Comment by puriaayush01** [comment]
Hi @dmdhrumilmistry . As per your suggestion I have tried using offat with Python 3.11. But Unfortunately I am getting the same error:
<img width="839" alt="image" src="https://github.com/OWASP/OFFAT/assets/110390926/b3114236-7ff6-4229-9bd5-3ec831eb05cd">

**Comment by puriaayush01** [comment]
@dmdhrumilmistry Is there an issue if I use another API for testing? Because I don't get any issue when I am using the https://petstore.swagger.io/v2/swagger.json file.

**Comment by dmdhrumilmistry** [comment]
This seems like parsing issue, I've made several changes to the tool in order fix dependency blocking issue by writing a new parser for openapi and swagger file. Make sure your swagger file contains `url`/`hosts` in it. It would be better if you can share your swagger file.
